/*
 * This source file was generated by the Gradle 'init' task
 */

package qangan.graph;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

import java.util.Arrays;
import java.util.Random;
import org.junit.jupiter.api.Test;

class GraphTest {

}
